version: '3.5'

services:
  cas1:
    container_name: cas1
    image: cassandra:latest
    restart: always
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=cluster1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
  cas2:
    container_name: cas2
    image: cassandra:latest
    ports:
        - 9043:9042
    restart: always
    depends_on:
      - cas1
    environment:
        - CASSANDRA_START_RPC=true
        - CASSANDRA_CLUSTER_NAME=cluster1
        - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
        - CASSANDRA_DC=datacenter1
        - CASSANDRA_SEEDS=cas1